using System.Text;

namespace ProtoCross.Tests.Conformance.Sweep;

/// <summary>A file the sweep writes, by its path from the repository root with forward slashes.</summary>
internal sealed record SweepFile(string RelativePath, string Text);

/// <summary>One fixture row: each field it sets, in order, with the value spelled as ProtoCross source.</summary>
internal sealed record SweepRow(IReadOnlyList<(string Field, string Value)> Values)
{
    public SweepRow(params (string Field, string Value)[] values)
        : this((IReadOnlyList<(string Field, string Value)>)values)
    {
    }

    public string Render(string table)
        => $"{table} {{ {string.Join(" ", Values.Select(value => $"{value.Field} = {value.Value};"))} }}";
}

/// <summary>
/// One table of a generated vector: the repeated field holding its rows, the method that walks them,
/// and the test that fills them in.
/// </summary>
/// <param name="Wrong">
/// The condition under which a row is wrong, as ProtoCross over <c>row</c>. Several lines are joined
/// with <c>or</c>, each on a line of its own.
/// </param>
internal sealed record SweepTable(
    string Receiver,
    string Field,
    string Method,
    IReadOnlyList<string> Wrong,
    string Description,
    IReadOnlyList<SweepRow> Rows);

/// <summary>
/// One generated conformance vector and the schema it owns, built up table by table and rendered
/// once.
/// </summary>
/// <remarks>
/// <para>
/// Every table is walked by a method that returns the index of the first row the backend got wrong,
/// or <c>-1</c>, and its test expects <c>-1</c>. A test per table rather than per value pair keeps
/// the vector to one test for each thing that can independently be wrong, while a failure still
/// names its row: each row carries its index in a comment, so the number in the failure is found
/// by searching the file.
/// </para>
/// <para>
/// The schema and the source are rendered from the same messages, so a field a fixture sets cannot
/// be missing from the schema, and a field the schema declares cannot go unused without the
/// generator having been told to declare it.
/// </para>
/// </remarks>
/// <param name="policyDirectory">
/// The directory under <c>vectors/</c> whose <c>protocross.config.xml</c> the vector compiles under,
/// or empty for the default. The vector goes in a <see cref="ArithmeticSweep.Directory"/> inside it,
/// so the ordinary upward search finds that policy and generated files stay apart from written ones.
/// </param>
internal sealed class SweepVector(string name, string policyDirectory, IReadOnlyList<string> summary)
{
    /// <summary>The first line of every generated file, which is how a leftover one is recognized.</summary>
    public const string Marker = "// Generated by tests/ProtoCross.Tests/Conformance/Sweep.";

    private const string Indent = "    ";

    private readonly List<(string Name, IReadOnlyList<string> Fields)> _messages = [];
    private readonly List<(string Receiver, string Text)> _methods = [];
    private readonly List<string> _tests = [];

    public string Name => name;

    /// <summary>Declares a message in the schema; each field is written as it is in a .proto file, without its number.</summary>
    public void Message(string message, params string[] fields) => _messages.Add((message, fields));

    public void Method(string receiver, string text) => _methods.Add((receiver, text));

    public void Table(SweepTable table)
    {
        Method(table.Receiver, Walk(table));
        _tests.Add(Test(table.Receiver, table.Method, table.Description, table.Field, table.Rows, "return -1"));
    }

    /// <summary>
    /// A test that hands a table's method one row it must not survive, under a policy that
    /// terminates rather than produce a value.
    /// </summary>
    public void Failure(SweepTable table, string description, SweepRow row)
        => _tests.Add(Test(table.Receiver, table.Method, description, table.Field, [row], "fail"));

    public IEnumerable<SweepFile> Files()
    {
        yield return new SweepFile($"tests/conformance/protos/{name}.proto", Schema());
        var directory = policyDirectory.Length == 0 ? ArithmeticSweep.Directory : $"{policyDirectory}/{ArithmeticSweep.Directory}";
        yield return new SweepFile($"tests/conformance/vectors/{directory}/{name}.pcross", Source());
    }

    private string Schema()
    {
        var text = new StringBuilder();
        Header(text);
        text.Append("syntax = \"proto3\";\n\npackage protocross.conformance;\n");

        foreach (var (message, fields) in _messages)
        {
            text.Append($"\nmessage {message} {{\n");
            for (var i = 0; i < fields.Count; i++)
            {
                text.Append($"  {fields[i]} = {i + 1};\n");
            }

            text.Append("}\n");
        }

        return text.ToString();
    }

    private string Source()
    {
        var text = new StringBuilder();
        Header(text);
        text.Append($"import proto \"{name}.proto\";\n");

        foreach (var receiver in _methods.Select(method => method.Receiver).Distinct())
        {
            text.Append($"\nextend {receiver} {{\n");
            text.Append(string.Join("\n", _methods.Where(method => method.Receiver == receiver).Select(method => method.Text)));
            text.Append("}\n");
        }

        foreach (var test in _tests)
        {
            text.Append('\n').Append(test);
        }

        return text.ToString().ReplaceLineEndings("\n");
    }

    private void Header(StringBuilder text)
    {
        text.Append($"{Marker} Do not edit it by hand: change the\n");
        text.Append("// generator, then run ArithmeticSweepTests with PROTOCROSS_REGENERATE_SWEEP=1 to rewrite it.\n");
        text.Append("//\n");
        foreach (var line in summary)
        {
            text.Append(line.Length == 0 ? "//\n" : $"// {line}\n");
        }

        text.Append('\n');
    }

    private static string Walk(SweepTable table)
    {
        var wrong = string.Join($"\n{Indent}{Indent}{Indent}{Indent}or ", table.Wrong);

        return $$"""
                fn {{table.Method}}() -> int32 {
                    var index: int32 = 0;

                    for row in {{table.Field}} {
                        if {{wrong}} {
                            return index;
                        }

                        index = index + 1;
                    }

                    return -1;
                }

            """;
    }

    private static string Test(
        string receiver,
        string method,
        string description,
        string field,
        IReadOnlyList<SweepRow> rows,
        string expectation)
    {
        var text = new StringBuilder();
        text.Append($"test {receiver}.{method} \"{description}\" {{\n");
        text.Append($"{Indent}receiver {{\n");

        for (var i = 0; i < rows.Count; i++)
        {
            text.Append($"{Indent}{Indent}{rows[i].Render(field)}");
            text.Append(rows.Count > 1 ? $" // {i}\n" : "\n");
        }

        text.Append($"{Indent}}}\n\n{Indent}expect {expectation};\n}}\n");
        return text.ToString();
    }
}
