<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ProtoCross.Cli</RootNamespace>
    <AssemblyName>protocross</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProtoCross.Core\ProtoCross.Core.csproj" />
    <ProjectReference Include="..\ProtoCross.Backend.CSharp\ProtoCross.Backend.CSharp.csproj" />
    <ProjectReference Include="..\ProtoCross.Backend.Cpp\ProtoCross.Backend.Cpp.csproj" />
  </ItemGroup>

</Project>
