using ProtoCross.Backend;
using ProtoCross.Ir;

namespace ProtoCross.Backend.Cpp;

/// <summary>
/// The fixed C++ support header emitted alongside generated code.
/// </summary>
/// <remarks>
/// <para>
/// Signed integer overflow is undefined behavior in C++, not wraparound. Compilers exploit that:
/// an optimizer is entitled to assume it never happens and delete the code that would follow.
/// ProtoCross's wrapping semantics therefore cannot be expressed as bare <c>a + b</c>; every
/// operation routes through these helpers, which perform the arithmetic in the unsigned domain
/// where modular behavior is well-defined.
/// </para>
/// <para>
/// All three overflow policies are emitted whichever one the project selected. The header is
/// therefore identical for every compilation, which is what lets sources built under different
/// policies share one translation unit, and every helper is <c>inline</c> so the linker discards
/// what nothing calls.
/// </para>
/// <para>
/// Overflow is detected by hand rather than through <c>__builtin_add_overflow</c>, which MSVC does
/// not provide. The predicates below are the portable forms, factored out so that the three policy
/// wrappers agree with each other by construction rather than by three separate proofs.
/// </para>
/// </remarks>
public static class CppRuntime
{
    public const string FileName = NameConventions.CppRuntimeName + ".h";

    // Lazy rather than a field initializer: Build() reads static tables declared further down,
    // and static field initializers run in declaration order.
    private static readonly Lazy<string> LazySource = new(Build);

    public static string Source => LazySource.Value;

    private static string Build()
    {
        var writer = new SourceWriter("  ");

        writer.WriteLine("// <auto-generated>");
        writer.WriteLine("//     ProtoCross C++ support header. Generated by protocross.");
        writer.WriteLine("//     Changes to this file will be lost when the code is regenerated.");
        writer.WriteLine("// </auto-generated>");
        writer.WriteLine();
        writer.WriteLine("#ifndef PROTOCROSS_RUNTIME_H_");
        writer.WriteLine("#define PROTOCROSS_RUNTIME_H_");
        writer.WriteLine();
        writer.WriteLine("#include <cstdint>");
        writer.WriteLine("#include <cstdio>");
        writer.WriteLine("#include <cstdlib>");
        writer.WriteLine("#include <limits>");
        writer.WriteLine();
        writer.WriteLine("// Requires C++20: the conversion from an unsigned type back to the corresponding");
        writer.WriteLine("// signed type is defined as two's complement (P0907R4). Earlier standards leave that");
        writer.WriteLine("// conversion implementation-defined.");
        writer.WriteLine("static_assert(__cplusplus >= 202002L, \"ProtoCross generated code requires C++20 or later.\");");
        writer.WriteLine();

        using (writer.Block("namespace protocross_runtime"))
        {
            EmitFailHelper(writer);
            EmitFailOverflowHelper(writer);

            foreach (var (signed, unsigned, suffix) in IntegerTypes)
            {
                writer.WriteLine($"// --- {signed} ---");
                writer.WriteLine();

                EmitOverflowPredicates(writer, signed, unsigned, suffix);

                foreach (var behavior in Behaviors)
                {
                    EmitBinaryHelper(writer, behavior, "add", "+", "addition", signed, unsigned, suffix);
                    EmitBinaryHelper(writer, behavior, "sub", "-", "subtraction", signed, unsigned, suffix);
                    EmitBinaryHelper(writer, behavior, "mul", "*", "multiplication", signed, unsigned, suffix);
                    EmitNegateHelper(writer, behavior, signed, unsigned, suffix);
                    EmitDivideHelper(writer, behavior, signed, unsigned, suffix);
                    EmitModuloHelper(writer, behavior, signed, suffix);
                    EmitDivideOrHelper(writer, behavior, signed, suffix);
                    EmitModuloOrHelper(writer, behavior, signed, suffix);
                    EmitDivideOrFailHelper(writer, behavior, signed, suffix);
                    EmitModuloOrFailHelper(writer, behavior, signed, suffix);
                }
            }

            writer.WriteLine("// --- explicit conversions (10.3) ---");
            writer.WriteLine();

            foreach (var (type, suffix, low, high) in FloatToIntegerTargets)
            {
                EmitFloatToIntegerHelper(writer, type, suffix, low, high);
            }

            EmitNarrowToFloatHelper(writer);

            writer.WriteLine("// --- enums (12) ---");
            writer.WriteLine();

            EmitEnumHelpers(writer);

            writer.WriteLine("// --- maps (14.2) ---");
            writer.WriteLine();

            EmitMapHelpers(writer);
        }

        writer.WriteLine();
        writer.WriteLine("#endif  // PROTOCROSS_RUNTIME_H_");

        return writer.ToString();
    }

    /// <summary>(signed C++ type, unsigned C++ type, ProtoCross helper suffix).</summary>
    private static readonly (string Signed, string Unsigned, string Suffix)[] IntegerTypes =
    [
        ("::std::int32_t", "::std::uint32_t", "i32"),
        ("::std::int64_t", "::std::uint64_t", "i64"),
        ("::std::uint32_t", "::std::uint32_t", "u32"),
        ("::std::uint64_t", "::std::uint64_t", "u64"),
    ];

    /// <summary>
    /// Floating-point to integer conversion targets: the C++ type, the ProtoCross helper suffix,
    /// and the two range guards.
    /// </summary>
    /// <remarks>
    /// The guards are not uniform, because the bound is not always representable as a
    /// <c>double</c>. Both 32-bit bounds are exact, so a strict comparison is right: a value just
    /// past the maximum truncates to the maximum anyway. The positive 64-bit bounds are not exact
    /// -- the nearest <c>double</c> above <c>int64_t</c>'s maximum is 2^63 -- so those guards are
    /// inclusive against the power of two instead.
    /// </remarks>
    private static readonly (string Type, string Suffix, string Low, string High)[] FloatToIntegerTargets =
    [
        ("::std::int32_t", "i32", "v < -2147483648.0", "v > 2147483647.0"),
        ("::std::int64_t", "i64", "v < -9223372036854775808.0", "v >= 9223372036854775808.0"),
        ("::std::uint32_t", "u32", "v <= 0.0", "v > 4294967295.0"),
        ("::std::uint64_t", "u64", "v <= 0.0", "v >= 18446744073709551616.0"),
    ];

    /// <summary>
    /// Emits a saturating, truncating conversion from <c>double</c> to one integer type.
    /// </summary>
    /// <remarks>
    /// A floating-point value outside the destination integer's range is undefined behavior in
    /// C++, not a wrapped or clamped result, so the bounds are checked before the conversion
    /// rather than relying on what the hardware happens to do.
    /// </remarks>
    private static void EmitFloatToIntegerHelper(
        SourceWriter writer,
        string type,
        string suffix,
        string low,
        string high)
    {
        writer.WriteLine("// Truncates toward zero, clamping to the type's bounds. NaN converts to zero.");
        using (writer.Block($"inline {type} trunc_sat_f64_to_{suffix}(double v)"))
        {
            using (writer.Block("if (v != v)"))
            {
                writer.WriteLine("return 0;");
            }

            writer.WriteLine();
            using (writer.Block($"if ({low})"))
            {
                writer.WriteLine($"return ::std::numeric_limits<{type}>::min();");
            }

            writer.WriteLine();
            using (writer.Block($"if ({high})"))
            {
                writer.WriteLine($"return ::std::numeric_limits<{type}>::max();");
            }

            writer.WriteLine();
            writer.WriteLine($"return static_cast<{type}>(v);");
        }

        writer.WriteLine();
    }

    /// <summary>
    /// Emits the narrowing conversion from <c>double</c> to <c>float</c>.
    /// </summary>
    /// <remarks>
    /// A <c>double</c> outside <c>float</c>'s range is undefined behavior in C++, where the
    /// baseline result is an infinity. The threshold is not <c>FLT_MAX</c>: under round-to-nearest
    /// a <c>double</c> between <c>FLT_MAX</c> and 2^128 - 2^103 rounds down to <c>FLT_MAX</c>
    /// rather than overflowing, so guarding at <c>FLT_MAX</c> would produce an infinity where
    /// every other target produces a finite value.
    /// </remarks>
    private static void EmitNarrowToFloatHelper(SourceWriter writer)
    {
        writer.WriteLine("// Narrows to float. Out of range yields an infinity rather than undefined behavior.");
        using (writer.Block("inline float narrow_f64_to_f32(double v)"))
        {
            writer.WriteLine("// 2^128 - 2^103: the smallest magnitude that rounds to infinity, not FLT_MAX.");
            writer.WriteLine("// Spelled as a hex float so the value is exact rather than nearest-parsed.");
            writer.WriteLine("constexpr double overflow = 0x1.ffffffp+127;");
            writer.WriteLine();
            using (writer.Block("if (v != v)"))
            {
                writer.WriteLine("return ::std::numeric_limits<float>::quiet_NaN();");
            }

            writer.WriteLine();
            using (writer.Block("if (v >= overflow)"))
            {
                writer.WriteLine("return ::std::numeric_limits<float>::infinity();");
            }

            writer.WriteLine();
            using (writer.Block("if (v <= -overflow)"))
            {
                writer.WriteLine("return -::std::numeric_limits<float>::infinity();");
            }

            writer.WriteLine();
            writer.WriteLine("return static_cast<float>(v);");
        }

        writer.WriteLine();
    }

    private static readonly ArithmeticBehavior[] Behaviors =
    [
        ArithmeticBehavior.Wrap,
        ArithmeticBehavior.Check,
        ArithmeticBehavior.Saturate,
    ];

    /// <summary>The helper-name prefix for one overflow policy.</summary>
    public static string Stem(ArithmeticBehavior behavior) => behavior switch
    {
        ArithmeticBehavior.Wrap => "wrap",
        ArithmeticBehavior.Check => "checked",
        ArithmeticBehavior.Saturate => "sat",
        _ => throw new ArgumentOutOfRangeException(nameof(behavior), behavior, "Unhandled arithmetic behavior."),
    };

    /// <summary>Whether a helper suffix names a signed type.</summary>
    private static bool IsSigned(string suffix) => suffix[0] == 'i';

    /// <summary>
    /// Emits the four <c>*_overflows_*</c> predicates for one type.
    /// </summary>
    /// <remarks>
    /// <para>
    /// These answer "would the mathematical result leave the range?" and nothing else, so all three
    /// policies share them. Each is written in the unsigned domain, where the arithmetic itself is
    /// defined, and then tested against the signed interpretation.
    /// </para>
    /// <para>
    /// Written by hand rather than through <c>__builtin_add_overflow</c>, which MSVC does not
    /// provide. Factoring them out is what makes the three policy wrappers agree with each other by
    /// construction rather than by three separate proofs.
    /// </para>
    /// <para>
    /// Multiplication is the one that resists a one-line rule. The usual test -- multiply, divide
    /// back, compare -- is correct except that the division itself can trap on <c>MIN / -1</c>, so
    /// the two <c>-1</c> cases are answered before any division happens.
    /// </para>
    /// </remarks>
    private static void EmitOverflowPredicates(SourceWriter writer, string signed, string unsigned, string suffix)
    {
        var min = $"::std::numeric_limits<{signed}>::min()";
        var max = $"::std::numeric_limits<{signed}>::max()";

        using (writer.Block($"inline bool add_overflows_{suffix}({signed} a, {signed} b)"))
        {
            if (IsSigned(suffix))
            {
                writer.WriteLine("// Overflow only when the operands share a sign that the result does not.");
                writer.WriteLine(
                    $"const {signed} r = static_cast<{signed}>(static_cast<{unsigned}>(a) + static_cast<{unsigned}>(b));");
                writer.WriteLine("return ((a ^ r) & (b ^ r)) < 0;");
            }
            else
            {
                writer.WriteLine($"return static_cast<{unsigned}>(a + b) < a;");
            }
        }

        writer.WriteLine();

        using (writer.Block($"inline bool sub_overflows_{suffix}({signed} a, {signed} b)"))
        {
            if (IsSigned(suffix))
            {
                writer.WriteLine("// Overflow only when the operands differ in sign and the result takes b's.");
                writer.WriteLine(
                    $"const {signed} r = static_cast<{signed}>(static_cast<{unsigned}>(a) - static_cast<{unsigned}>(b));");
                writer.WriteLine("return ((a ^ b) & (a ^ r)) < 0;");
            }
            else
            {
                writer.WriteLine("return a < b;");
            }
        }

        writer.WriteLine();

        using (writer.Block($"inline bool mul_overflows_{suffix}({signed} a, {signed} b)"))
        {
            using (writer.Block("if (a == 0 || b == 0)"))
            {
                writer.WriteLine("return false;");
            }

            writer.WriteLine();

            if (IsSigned(suffix))
            {
                writer.WriteLine("// Answered before the division below, which would itself trap on MIN / -1.");
                using (writer.Block("if (a == -1)"))
                {
                    writer.WriteLine($"return b == {min};");
                }

                writer.WriteLine();
                using (writer.Block("if (b == -1)"))
                {
                    writer.WriteLine($"return a == {min};");
                }

                writer.WriteLine();
                writer.WriteLine(
                    $"const {signed} r = static_cast<{signed}>(static_cast<{unsigned}>(a) * static_cast<{unsigned}>(b));");
                writer.WriteLine("return r / a != b;");
            }
            else
            {
                writer.WriteLine($"return b > {max} / a;");
            }
        }

        writer.WriteLine();

        using (writer.Block($"inline bool neg_overflows_{suffix}({signed} a)"))
        {
            if (IsSigned(suffix))
            {
                writer.WriteLine($"return a == {min};");
            }
            else
            {
                writer.WriteLine("// Any non-zero unsigned value negates to something unrepresentable. No call");
                writer.WriteLine("// site can reach this: negating an unsigned value is PC0052.");
                writer.WriteLine("return a != 0;");
            }
        }

        writer.WriteLine();
    }

    /// <summary>Emits <c>add</c>, <c>sub</c>, or <c>mul</c> for one type under one policy.</summary>
    private static void EmitBinaryHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string name,
        string op,
        string description,
        string signed,
        string unsigned,
        string suffix)
    {
        var stem = Stem(behavior);
        var wrapped =
            $"static_cast<{signed}>(static_cast<{unsigned}>(a) {op} static_cast<{unsigned}>(b))";

        writer.WriteLine($"// {char.ToUpperInvariant(description[0])}{description[1..]}, {Describe(behavior)}.");
        using (writer.Block($"inline {signed} {stem}_{name}_{suffix}({signed} a, {signed} b)"))
        {
            if (behavior != ArithmeticBehavior.Wrap)
            {
                using (writer.Block($"if ({name}_overflows_{suffix}(a, b))"))
                {
                    writer.WriteLine(behavior == ArithmeticBehavior.Check
                        ? $"fail_overflow(\"{description}\");"
                        : SaturationBound(signed, suffix, name));
                }

                writer.WriteLine();
            }

            writer.WriteLine($"return {wrapped};");
        }

        writer.WriteLine();
    }

    /// <summary>
    /// The clamp for an operation already established to overflow.
    /// </summary>
    /// <remarks>
    /// Derived from the operands rather than from the wrapped result. Addition overflows only when
    /// both operands share a sign, so either one names the bound; subtraction overflows away from
    /// <c>b</c>'s sign; a product's sign is the exclusive-or of its operands', neither of which
    /// can be zero here. Unsigned arithmetic can only leave the range at one end.
    /// </remarks>
    private static string SaturationBound(string signed, string suffix, string name)
    {
        var min = $"::std::numeric_limits<{signed}>::min()";
        var max = $"::std::numeric_limits<{signed}>::max()";

        if (!IsSigned(suffix))
        {
            return name == "sub" ? $"return {min};" : $"return {max};";
        }

        return name switch
        {
            "add" => $"return b > 0 ? {max} : {min};",
            "sub" => $"return b > 0 ? {min} : {max};",
            "mul" => $"return (a < 0) != (b < 0) ? {min} : {max};",
            _ => throw new ArgumentOutOfRangeException(nameof(name), name, "Not a saturating binary operation."),
        };
    }

    private static void EmitNegateHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string signed,
        string unsigned,
        string suffix)
    {
        var stem = Stem(behavior);

        writer.WriteLine($"// Negation, {Describe(behavior)}.");
        using (writer.Block($"inline {signed} {stem}_neg_{suffix}({signed} a)"))
        {
            if (behavior != ArithmeticBehavior.Wrap)
            {
                using (writer.Block($"if (neg_overflows_{suffix}(a))"))
                {
                    writer.WriteLine(behavior == ArithmeticBehavior.Check
                        ? "fail_overflow(\"negation\");"
                        : $"return ::std::numeric_limits<{signed}>::max();");
                }

                writer.WriteLine();
            }

            writer.WriteLine($"return static_cast<{signed}>(0u - static_cast<{unsigned}>(a));");
        }

        writer.WriteLine();
    }

    /// <summary>
    /// Emits the termination helper behind the checked overflow policy.
    /// </summary>
    /// <remarks>
    /// Separate from <c>fail</c> only because the two say different things: one reports a divisor
    /// that was zero, the other a result that did not fit. Both stop the process the same way and
    /// with the same exit code, so a test can pin either through <c>expect fail</c>.
    /// </remarks>
    private static void EmitFailOverflowHelper(SourceWriter writer)
    {
        writer.WriteLine("// Reached only under the checked overflow policy, where the project declared that");
        writer.WriteLine("// an unrepresentable result is not to be papered over.");
        using (writer.Block("[[noreturn]] inline void fail_overflow(const char* operation)"))
        {
            writer.WriteLine("::std::fputs(\"ProtoCross: \", stderr);");
            writer.WriteLine("::std::fputs(operation, stderr);");
            writer.WriteLine("::std::fputs(\" overflowed\\n\", stderr);");
            writer.WriteLine("::std::fflush(stderr);");
            writer.WriteLine($"::std::_Exit({FailExitCode});");
        }

        writer.WriteLine();
    }

    private static void EmitDivideOrFailHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string signed,
        string suffix)
    {
        var stem = Stem(behavior);

        writer.WriteLine("// Division that terminates the process on a zero divisor.");
        using (writer.Block($"inline {signed} {stem}_div_or_fail_{suffix}({signed} a, {signed} b)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("fail(\"division\");");
            }

            writer.WriteLine();
            writer.WriteLine($"return {stem}_div_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    private static void EmitModuloOrFailHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string signed,
        string suffix)
    {
        var stem = Stem(behavior);

        writer.WriteLine("// Remainder that terminates the process on a zero divisor.");
        using (writer.Block($"inline {signed} {stem}_mod_or_fail_{suffix}({signed} a, {signed} b)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("fail(\"modulo\");");
            }

            writer.WriteLine();
            writer.WriteLine($"return {stem}_mod_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    /// <summary>
    /// Emits the form used when the author supplied an <c>on_zero</c> fallback, which takes the
    /// fallback as something to call.
    /// </summary>
    /// <remarks>
    /// The call site writes the fallback as a lambda, so it is evaluated only for a zero divisor, as a
    /// map lookup's is only for a missing key (<see cref="EmitMapHelpers"/>). A fallback passed as a
    /// value is evaluated before the divisor is looked at, so one that would end the program ended it
    /// whatever the divisor was (spec 10.2.1).
    /// </remarks>
    private static void EmitDivideOrHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string signed,
        string suffix)
    {
        var stem = Stem(behavior);

        writer.WriteLine("// Division that yields on_zero() instead of failing, calling it only for a zero divisor.");
        writer.WriteLine("template <typename OnZero>");
        using (writer.Block(
            $"inline {signed} {stem}_div_or_{suffix}({signed} a, {signed} b, OnZero on_zero)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("return on_zero();");
            }

            writer.WriteLine();
            writer.WriteLine($"return {stem}_div_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    private static void EmitModuloOrHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string signed,
        string suffix)
    {
        var stem = Stem(behavior);

        writer.WriteLine("// Remainder that yields on_zero() instead of failing, calling it only for a zero divisor.");
        writer.WriteLine("template <typename OnZero>");
        using (writer.Block(
            $"inline {signed} {stem}_mod_or_{suffix}({signed} a, {signed} b, OnZero on_zero)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("return on_zero();");
            }

            writer.WriteLine();
            writer.WriteLine($"return {stem}_mod_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    private static void EmitDivideHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string signed,
        string unsigned,
        string suffix)
    {
        var stem = Stem(behavior);

        writer.WriteLine("// Reached only when the divisor is a non-zero literal, so b is never 0.");
        using (writer.Block($"inline {signed} {stem}_div_{suffix}({signed} a, {signed} b)"))
        {
            if (IsSigned(suffix))
            {
                writer.WriteLine("// MIN / -1 is the one division that overflows. The -1 case is answered here,");
                writer.WriteLine("// before the divide instruction, which would otherwise trap.");
                using (writer.Block("if (b == -1)"))
                {
                    if (behavior != ArithmeticBehavior.Wrap)
                    {
                        using (writer.Block($"if (a == ::std::numeric_limits<{signed}>::min())"))
                        {
                            writer.WriteLine(behavior == ArithmeticBehavior.Check
                                ? "fail_overflow(\"division\");"
                                : $"return ::std::numeric_limits<{signed}>::max();");
                        }

                        writer.WriteLine();
                    }

                    writer.WriteLine($"return static_cast<{signed}>(0u - static_cast<{unsigned}>(a));");
                }

                writer.WriteLine();
            }

            writer.WriteLine("return a / b;");
        }

        writer.WriteLine();
    }

    private static void EmitModuloHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string signed,
        string suffix)
    {
        var stem = Stem(behavior);

        writer.WriteLine("// Reached only when the divisor is a non-zero literal, so b is never 0.");
        using (writer.Block($"inline {signed} {stem}_mod_{suffix}({signed} a, {signed} b)"))
        {
            if (IsSigned(suffix))
            {
                writer.WriteLine("// MIN % -1 traps on the same instruction as the quotient, but unlike the");
                writer.WriteLine("// quotient the remainder is 0, which every type can represent. No policy");
                writer.WriteLine("// differs here.");
                using (writer.Block("if (b == -1)"))
                {
                    writer.WriteLine("return 0;");
                }

                writer.WriteLine();
            }

            writer.WriteLine("return a % b;");
        }

        writer.WriteLine();
    }

    private static string Describe(ArithmeticBehavior behavior) => behavior switch
    {
        ArithmeticBehavior.Wrap => "wrapping on overflow",
        ArithmeticBehavior.Check => "terminating the process on overflow",
        ArithmeticBehavior.Saturate => "clamping on overflow",
        _ => throw new ArgumentOutOfRangeException(nameof(behavior), behavior, "Unhandled arithmetic behavior."),
    };

    /// <summary>
    /// Exit code of a program stopped by <c>on_zero fail</c>. <c>EX_SOFTWARE</c> from
    /// <c>sysexits.h</c>, and normative: every backend reports the same code (spec 10.2.1).
    /// </summary>
    public const int FailExitCode = 70;

    /// <summary>
    /// Emits the deterministic-termination helper behind <c>on_zero fail</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Writing to stderr is the one place generated code performs I/O. Spec 20 bans I/O in method
    /// bodies; this is a fatal-error path, not behavior, and stopping with no explanation would be
    /// far harder to diagnose.
    /// </para>
    /// <para>
    /// <c>_Exit</c> rather than <c>abort</c>. <c>abort</c> raises <c>SIGABRT</c>, which means two
    /// things this needs to avoid: the default handler hands the process to the platform's crash
    /// reporter -- a dialog and a postmortem debugger prompt on Windows -- and a program that
    /// installs its own <c>SIGABRT</c> handler could <em>resume</em>, which would defeat the whole
    /// point of the clause. <c>_Exit</c> can be intercepted by nothing, runs no destructors or
    /// atexit handlers, and reports the exit code chosen here rather than a signal.
    /// </para>
    /// </remarks>
    /// <summary>
    /// Emits what a conversion to an enum makes of a number the enum does not name: a fallback, or
    /// termination (spec 12).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Templates over the enum, given protoc's <c>_IsValid</c> for it by address, so one helper serves
    /// every enum and the call site is the only thing that names one. The value is taken already cast
    /// to the enum, which protoc declares with <c>int</c> beneath it, so any number survives the cast.
    /// </para>
    /// <para>
    /// A fallback is taken as something to call, which the call site writes as a lambda, so it is
    /// evaluated only for a number the schema does not name, as an <c>on_zero</c> fallback is only for
    /// a zero divisor (<see cref="EmitDivideOrHelper"/>).
    /// </para>
    /// <para>
    /// The failure writes the line the C# runtime writes, naming the enum by its protobuf name, since
    /// protoc gives the two targets different names for it.
    /// </para>
    /// </remarks>
    private static void EmitEnumHelpers(SourceWriter writer)
    {
        writer.WriteLine("// Reached from an 'on_unknown fail' clause, and from a conversion to a closed enum");
        writer.WriteLine("// that states no fallback.");
        using (writer.Block("[[noreturn]] inline void fail_unnamed(const char* enum_name, ::std::int32_t number)"))
        {
            writer.WriteLine("::std::fputs(\"ProtoCross: \", stderr);");
            writer.WriteLine("::std::fputs(enum_name, stderr);");
            writer.WriteLine("::std::fprintf(stderr, \" has no value numbered %ld\\n\", static_cast<long>(number));");
            writer.WriteLine("::std::fflush(stderr);");
            writer.WriteLine($"::std::_Exit({FailExitCode});");
        }

        writer.WriteLine();
        writer.WriteLine("template <typename E, typename Fallback>");
        using (writer.Block("inline E named_or(E value, bool (*is_named)(int), Fallback fallback)"))
        {
            writer.WriteLine("return is_named(static_cast<int>(value)) ? value : fallback();");
        }

        writer.WriteLine();
        writer.WriteLine("template <typename E>");
        using (writer.Block("inline E named_or_fail(E value, bool (*is_named)(int), const char* enum_name)"))
        {
            using (writer.Block("if (!is_named(static_cast<int>(value)))"))
            {
                writer.WriteLine("fail_unnamed(enum_name, static_cast<::std::int32_t>(value));");
            }

            writer.WriteLine();
            writer.WriteLine("return value;");
        }

        writer.WriteLine();
    }

    /// <summary>The map operations whose ProtoCross semantics protobuf's <c>Map</c> does not already provide (spec 14.2).</summary>
    /// <remarks>
    /// <para>
    /// Templates over the map, so this header names no protobuf type and needs no protobuf include:
    /// whatever <c>Map</c> a call site passes is the one it reads.
    /// </para>
    /// <para>
    /// A lookup with a fallback takes the fallback as something to call, which the call site writes as
    /// a lambda, so it is evaluated only when the key is missing.
    /// </para>
    /// <para>
    /// Both lookups return the value by value, because what a lookup gives is a value (spec 14.2). A
    /// fallback is a temporary, and a reference to it would outlive it. A lookup that fails could give a
    /// reference into the map instead and save a copy, and review found that wrong. A lookup passed to
    /// a <c>mut fn</c> is then the map's own storage, and the method changing the map changes its
    /// read-only argument: <c>observe(items[1] on_missing fail)</c> sees a store to <c>items[1]</c> the
    /// method makes after it was called. A call passes an argument that is not a place as written,
    /// because it is a temporary of its own (spec 18), and returning by value is what keeps a lookup
    /// one. A copy at that call alone would have kept the reference everywhere else, and left every
    /// future place a lookup can be held across a change to ask the question again.
    /// </para>
    /// <para>
    /// Equality compares each value with its own <c>==</c>, as the C# runtime does, so a NaN equals
    /// nothing in either.
    /// </para>
    /// <para>
    /// A merge takes its source by value. The source may be inside the target -- a map held by one of
    /// the target's own elements, <c>held.merge((held[1] on_missing fail).items)</c> -- and storing that
    /// element replaces the message the source lives in while the merge is still reading it. A copy
    /// taken before the first store is read instead. Merging a map into itself changes nothing either
    /// way.
    /// </para>
    /// </remarks>
    private static void EmitMapHelpers(SourceWriter writer)
    {
        writer.WriteLine("// Reached from an 'on_missing fail' clause.");
        using (writer.Block("[[noreturn]] inline void fail_missing(const char* map_name)"))
        {
            writer.WriteLine("::std::fputs(\"ProtoCross: \", stderr);");
            writer.WriteLine("::std::fputs(map_name, stderr);");
            writer.WriteLine("::std::fputs(\" has no such key\\n\", stderr);");
            writer.WriteLine("::std::fflush(stderr);");
            writer.WriteLine($"::std::_Exit({FailExitCode});");
        }

        writer.WriteLine();
        writer.WriteLine("template <typename Map, typename Key, typename Fallback>");
        using (writer.Block("inline typename Map::mapped_type value_or(const Map& map, const Key& key, Fallback fallback)"))
        {
            writer.WriteLine("auto found = map.find(key);");
            using (writer.Block("if (found != map.end())"))
            {
                writer.WriteLine("return found->second;");
            }

            writer.WriteLine();
            writer.WriteLine("return fallback();");
        }

        writer.WriteLine();
        writer.WriteLine("template <typename Map, typename Key>");
        using (writer.Block("inline typename Map::mapped_type found_or_fail(const Map& map, const Key& key, const char* map_name)"))
        {
            writer.WriteLine("auto found = map.find(key);");
            using (writer.Block("if (found == map.end())"))
            {
                writer.WriteLine("fail_missing(map_name);");
            }

            writer.WriteLine();
            writer.WriteLine("return found->second;");
        }

        writer.WriteLine();
        writer.WriteLine("template <typename Map, typename Key, typename Value>");
        using (writer.Block("inline void add_if_absent(Map& map, const Key& key, const Value& value)"))
        {
            using (writer.Block("if (map.find(key) == map.end())"))
            {
                writer.WriteLine("map[key] = value;");
            }
        }

        writer.WriteLine();
        writer.WriteLine("template <typename Map, typename Key, typename Value>");
        using (writer.Block("inline void replace_if_present(Map& map, const Key& key, const Value& value)"))
        {
            writer.WriteLine("auto found = map.find(key);");
            using (writer.Block("if (found != map.end())"))
            {
                writer.WriteLine("found->second = value;");
            }
        }

        writer.WriteLine();
        writer.WriteLine("template <typename Map>");
        using (writer.Block("inline void merge(Map& target, Map source)"))
        {
            using (writer.Block("for (const auto& entry : source)"))
            {
                writer.WriteLine("target[entry.first] = entry.second;");
            }
        }

        writer.WriteLine();
        writer.WriteLine("template <typename Map>");
        using (writer.Block("inline bool maps_equal(const Map& left, const Map& right)"))
        {
            using (writer.Block("if (left.size() != right.size())"))
            {
                writer.WriteLine("return false;");
            }

            writer.WriteLine();
            using (writer.Block("for (const auto& entry : left)"))
            {
                writer.WriteLine("auto found = right.find(entry.first);");
                using (writer.Block("if (found == right.end() || !(found->second == entry.second))"))
                {
                    writer.WriteLine("return false;");
                }
            }

            writer.WriteLine();
            writer.WriteLine("return true;");
        }

        writer.WriteLine();
    }

    private static void EmitFailHelper(SourceWriter writer)
    {
        writer.WriteLine("// Reached only from an 'on_zero fail' clause, where the author declared that");
        writer.WriteLine("// no substitute value is correct.");
        using (writer.Block("[[noreturn]] inline void fail(const char* operation)"))
        {
            writer.WriteLine("::std::fputs(\"ProtoCross: \", stderr);");
            writer.WriteLine("::std::fputs(operation, stderr);");
            writer.WriteLine("::std::fputs(\" by zero\\n\", stderr);");
            writer.WriteLine("::std::fflush(stderr);");
            writer.WriteLine();
            writer.WriteLine("// Not abort(): SIGABRT is catchable, and its default handler raises a crash");
            writer.WriteLine("// report. Generated library code must not be able to do either.");
            writer.WriteLine($"::std::_Exit({FailExitCode});");
        }

        writer.WriteLine();
    }
}
