using System.Globalization;
using System.Text;
using ProtoCross.Backend;
using ProtoCross.Diagnostics;
using ProtoCross.Ir;
using ProtoCross.Types;

namespace ProtoCross.Backend.CSharp;

public sealed partial class CSharpBackend
{
    public IReadOnlyList<GeneratedFile> EmitTests(
        IrModule module,
        BackendOptions options,
        DiagnosticBag diagnostics)
    {
        if (module.Tests.Count == 0)
        {
            return [];
        }

        var sourceName = Path.GetFileNameWithoutExtension(options.SourceFileName);
        var writer = new SourceWriter();
        WriteTestHeader(writer, options);

        // Names are allocated once and reused, because an 'expect fail' test needs the same
        // identifier in three places: the fact, the key it passes to the child process, and the
        // case label the child dispatches on.
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var methodNames = module.Tests.ToDictionary(test => test, test => UniqueTestMethodName(test, usedNames));
        var failTests = module.Tests.Where(t => t.Expectation is IrTestFailExpectation).ToList();
        var placement = new Placement(options.ProjectNamespace);

        using (writer.Block("namespace ProtoCross.GeneratedTests"))
        {
            var className = ToIdentifier(sourceName) + "ProtoCrossTests";
            using var classScope = writer.Block($"public sealed class {className}");

            var first = true;
            foreach (var test in module.Tests)
            {
                if (!first)
                {
                    writer.WriteLine();
                }

                first = false;
                EmitTest(writer, test, methodNames[test], sourceName, placement);
            }

            if (failTests.Count > 0)
            {
                writer.WriteLine();
                EmitFailTestDispatcher(writer, failTests, methodNames, sourceName, placement);
            }
        }

        var fileName = sourceName + NameConventions.TestsSuffix + ".g.cs";

        // The support file is emitted only when something needs it, so a source with no 'expect
        // fail' test does not gain a file that starts child processes.
        return failTests.Count > 0
            ?
            [
                new GeneratedFile(CSharpTestRuntime.FileName, CSharpTestRuntime.Source),
                new GeneratedFile(fileName, writer.ToString()),
            ]
            : [new GeneratedFile(fileName, writer.ToString())];
    }

    public IReadOnlyList<GeneratedFile> EmitTestProject(
        ScaffoldOptions options,
        DiagnosticBag diagnostics)
        => [new GeneratedFile(CSharpTestProject.FileName, CSharpTestProject.Build(options))];

    private static void WriteTestHeader(SourceWriter writer, BackendOptions options)
    {
        writer.WriteLine("// <auto-generated>");
        writer.WriteLine($"//     Generated by protocross from {options.SourceFileName}.");
        writer.WriteLine("//     ProtoCross unit tests for generated behavior.");
        foreach (var line in options.PolicyDescription)
        {
            writer.WriteLine($"//     {line}");
        }

        writer.WriteLine("//     Changes to this file will be lost when the code is regenerated.");
        writer.WriteLine("// </auto-generated>");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("// Every expectation is asserted the same way, whatever its type, so that the");
        writer.WriteLine("// emitted assertion follows from the declared 'expect return' rather than from the");
        writer.WriteLine("// backend guessing which overload reads better.");
        writer.WriteLine("#pragma warning disable xUnit2004 // Do not use Assert.Equal for boolean conditions");
        writer.WriteLine();
    }

    private static void EmitTest(
        SourceWriter writer, IrTest test, string methodName, string sourceName, Placement placement)
    {
        // The display name is the backend-independent identity rather than the mangled method name,
        // so a conformance harness reading the test log sees the same string every backend reports.
        writer.WriteLine($"[global::Xunit.Fact(DisplayName = {FormatString(test.Identity)})]");
        using var scope = writer.Block($"public void {methodName}()");

        if (test.Expectation is IrTestFailExpectation)
        {
            EmitFailTest(writer, test, methodName, sourceName);
            return;
        }

        if (test.Expectation is not IrTestReturnExpectation returnExpectation)
        {
            throw new ArgumentOutOfRangeException(nameof(test), test.Expectation, "Unhandled C# test expectation.");
        }

        EmitReceiverCreation(writer, test.Receiver, placement);
        writer.WriteLine(
            "global::Xunit.Assert.Equal("
            + $"{Expression(returnExpectation.Value, placement, "receiver")}, {Invocation(test, placement)});");
    }

    /// <summary>
    /// Emits an <c>expect fail</c> test. What it asserts is that the call does not return, which no
    /// assertion inside the same process can observe, so the call happens in a child process and
    /// this only inspects how that process ended.
    /// </summary>
    private static void EmitFailTest(SourceWriter writer, IrTest test, string methodName, string sourceName)
    {
        var key = FormatString(sourceName + ":" + methodName);

        writer.WriteLine($"var unexpected = {CSharpTestRuntime.TypeName}.DescribeExpectFail({key});");
        writer.WriteLine("global::Xunit.Assert.True(");
        writer.Indent();
        writer.WriteLine("unexpected is null,");
        writer.WriteLine($"{FormatString(test.Identity + " expected terminal failure, but ")} + unexpected);");
        writer.Unindent();
    }

    /// <summary>
    /// Emits the module initializer a child process lands in. It runs before the test host's entry
    /// point, so a child never starts a normal test run.
    /// </summary>
    private static void EmitFailTestDispatcher(
        SourceWriter writer,
        IReadOnlyList<IrTest> failTests,
        IReadOnlyDictionary<IrTest, string> methodNames,
        string sourceName,
        Placement placement)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Runs the single 'expect fail' test this process was launched for, and returns");
        writer.WriteLine("/// immediately during an ordinary test run.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");
        using var scope = writer.Block("internal static void RunRequestedProtoCrossFailTest()");

        writer.WriteLine(
            $"var requested = {CSharpTestRuntime.TypeName}.RequestedTest({FormatString(sourceName)});");
        using (writer.Block("if (requested is null)"))
        {
            writer.WriteLine("return;");
        }

        writer.WriteLine();
        writer.WriteLine($"var key = {FormatString(sourceName + ":")} + requested;");
        writer.WriteLine();
        writer.WriteLine("// The parent reads these two markers rather than an exit code: how a host");
        writer.WriteLine("// reports a fail-fast, and how long it takes to, is not something a test can");
        writer.WriteLine("// depend on. The first says the body ran; the second says it came back, which");
        writer.WriteLine("// is exactly the failure an 'expect fail' test is looking for.");
        writer.WriteLine($"global::System.Console.Out.WriteLine({CSharpTestRuntime.TypeName}.StartedMarker + key);");
        writer.WriteLine("global::System.Console.Out.Flush();");
        writer.WriteLine();
        using (writer.Block("switch (requested)"))
        {
            foreach (var test in failTests)
            {
                // Each case gets its own block: the receiver local would otherwise collide with the
                // one declared by the case before it.
                writer.WriteLine($"case {FormatString(methodNames[test])}:");
                writer.WriteLine("{");
                writer.Indent();

                EmitReceiverCreation(writer, test.Receiver, placement);

                // The call is expected not to return, so its result is deliberately unused.
                writer.WriteLine(test.Target.ReturnType is VoidType
                    ? $"{Invocation(test, placement)};"
                    : $"_ = {Invocation(test, placement)};");
                writer.WriteLine("break;");

                writer.Unindent();
                writer.WriteLine("}");
                writer.WriteLine();
            }

            writer.WriteLine("default:");
            writer.Indent();
            writer.WriteLine($"global::System.Environment.Exit({CSharpTestRuntime.TypeName}.UnknownTest);");
            writer.WriteLine("break;");
            writer.Unindent();
        }

        writer.WriteLine();
        writer.WriteLine("// Reached only when the method returned instead of terminating the process.");
        writer.WriteLine($"global::System.Console.Out.WriteLine({CSharpTestRuntime.TypeName}.ReturnedMarker + key);");
        writer.WriteLine("global::System.Console.Out.Flush();");
        writer.WriteLine($"global::System.Environment.Exit({CSharpTestRuntime.TypeName}.DidNotTerminate);");
    }

    /// <summary>The call under test, against the local named <c>receiver</c>.</summary>
    private static string Invocation(IrTest test, Placement placement)
    {
        var arguments = new List<string> { "receiver" };
        arguments.AddRange(test.Arguments.Select(a => Expression(a.Value, placement, "receiver")));

        return $"{placement.QualifiedClassOf(test.Target.Receiver)}."
            + $"{placement.MethodNameOf(test.Target)}({string.Join(", ", arguments)})";
    }

    /// <summary>Declares the local named <c>receiver</c> that a test calls its method on.</summary>
    /// <remarks>
    /// A fixture's values cannot name a receiver (spec 25.3), so <c>receiver</c> is never read inside
    /// its own initializer.
    /// </remarks>
    private static void EmitReceiverCreation(SourceWriter writer, IrMessageLiteral receiver, Placement placement)
        => writer.WriteLine($"var receiver = {MessageLiteral(receiver, placement, "receiver")};");

    private static string UniqueTestMethodName(IrTest test, HashSet<string> usedNames)
    {
        var baseName = ToIdentifier($"{test.Target.Receiver.Name}_{test.Target.Name}_{test.Name}");
        var candidate = baseName;
        var suffix = 2;
        while (!usedNames.Add(candidate))
        {
            candidate = baseName + suffix.ToString(CultureInfo.InvariantCulture);
            suffix++;
        }

        return candidate;
    }

    private static string ToIdentifier(string text)
    {
        var builder = new StringBuilder(text.Length);
        var capitalizeNext = true;

        foreach (var c in text)
        {
            if (char.IsLetterOrDigit(c))
            {
                builder.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                capitalizeNext = false;
                continue;
            }

            capitalizeNext = true;
        }

        if (builder.Length == 0 || !char.IsLetter(builder[0]))
        {
            builder.Insert(0, 'T');
        }

        var identifier = builder.ToString();
        return ReservedWords.Contains(identifier) ? "@" + identifier : identifier;
    }
}
