using Google.Protobuf.Reflection;
using ProtoCross.Backend;
using ProtoCross.Diagnostics;
using ProtoCross.Ir;
using ProtoCross.Semantics;
using ProtoCross.Types;

namespace ProtoCross.Backend.CSharp;

/// <summary>
/// Emits C# extension methods over the generated protobuf classes.
/// </summary>
/// <remarks>
/// <para>
/// Spec 24.1 leaves the integration shape open. This backend uses extension methods because they
/// impose nothing on the protobuf codegen: the generated messages may live in another assembly,
/// and nothing here depends on them being partial.
/// </para>
/// <para>
/// Arithmetic is emitted inside <c>unchecked(...)</c>. C# integer arithmetic is already unchecked
/// by default, but a consumer can set <c>CheckForOverflowUnderflow</c> at the project level, which
/// would silently turn wrapping into an exception. Stating it per-operation makes the semantics a
/// property of the generated code rather than of the consumer's build.
/// </para>
/// </remarks>
public sealed partial class CSharpBackend : ITestProjectScaffold
{
    public string Name => "csharp";

    public IReadOnlyList<GeneratedFile> Emit(
        IrModule module,
        BackendOptions options,
        DiagnosticBag diagnostics)
    {
        var writer = new SourceWriter();
        WriteHeader(writer, options);

        var placement = new Placement(options.ProjectNamespace);
        var byNamespace = module.Methods
            .GroupBy(m => placement.NamespaceOf(m.Receiver))
            .OrderBy(g => g.Key, StringComparer.Ordinal);

        foreach (var namespaceGroup in byNamespace)
        {
            var hasNamespace = !string.IsNullOrEmpty(namespaceGroup.Key);
            IDisposable? namespaceScope = hasNamespace ? writer.Block($"namespace {namespaceGroup.Key}") : null;

            var byPart = namespaceGroup
                .GroupBy(m => placement.PartOf(m.Receiver), StringComparer.Ordinal)
                .OrderBy(g => g.Key, StringComparer.Ordinal);

            var firstClass = true;
            foreach (var part in byPart)
            {
                if (!firstClass)
                {
                    writer.WriteLine();
                }

                firstClass = false;

                // Ordered by receiver and otherwise left in the order they were declared, so a
                // project's one part lists each receiver's methods together.
                var methods = part.OrderBy(m => m.Receiver.FullName, StringComparer.Ordinal).ToList();
                EmitExtensionClass(writer, placement.ClassOf(methods[0].Receiver), methods, placement);
            }

            namespaceScope?.Dispose();
        }

        var fileName = Path.GetFileNameWithoutExtension(options.SourceFileName) + ".g.cs";
        return
        [
            new GeneratedFile(CSharpRuntime.FileName, CSharpRuntime.Source),
            new GeneratedFile(fileName, writer.ToString()),
        ];
    }

    private static void WriteHeader(SourceWriter writer, BackendOptions options)
    {
        writer.WriteLine("// <auto-generated>");
        writer.WriteLine($"//     Generated by protocross from {options.SourceFileName}.");
        foreach (var line in options.PolicyDescription)
        {
            writer.WriteLine($"//     {line}");
        }

        writer.WriteLine("//     Changes to this file will be lost when the code is regenerated.");
        writer.WriteLine("// </auto-generated>");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        writer.WriteLine("// A ProtoCross comparison is emitted exactly as written, including 'x != x', which is");
        writer.WriteLine("// how a NaN is detected. Generated code must build in a project that treats");
        writer.WriteLine("// warnings as errors.");
        writer.WriteLine("#pragma warning disable CS1718 // Comparison made to same variable");
        writer.WriteLine();
    }

    /// <summary>
    /// Emits this source's part of the extension class named <paramref name="className"/>, holding
    /// <paramref name="methods"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The class is <c>partial</c> because it is not one source's: beside the message it is one
    /// receiver's, and in a project's namespace it is the project's. Each source is emitted to a file
    /// of its own (#27), so two sources that extend one message each declare the class, and a
    /// consumer compiles both into one assembly. A class per source was the alternative, and would
    /// have put the file a method happens to be declared in into the name every caller spells, so
    /// moving a method between files would break the callers of it.
    /// </para>
    /// <para>
    /// Every part carries the summary, because no source can know whether another declares the
    /// class too. The compiler accepts a summary on each part of a partial type without a warning,
    /// under <c>GenerateDocumentationFile</c> and <c>TreatWarningsAsErrors</c> alike, and repeats it
    /// in the documentation file. It names the messages this part extends, which beside the message
    /// is the one the class is named after.
    /// </para>
    /// </remarks>
    private static void EmitExtensionClass(
        SourceWriter writer,
        string className,
        IReadOnlyList<IrMethod> methods,
        Placement placement)
    {
        var receivers = methods.Select(method => $"<c>{method.Receiver.FullName}</c>").Distinct(StringComparer.Ordinal);

        writer.WriteLine($"/// <summary>ProtoCross behavior for {string.Join(", ", receivers)}.</summary>");
        using var classScope = writer.Block($"public static partial class {className}");

        var first = true;
        foreach (var method in methods)
        {
            if (!first)
            {
                writer.WriteLine();
            }

            first = false;
            EmitMethod(writer, method, placement);
        }
    }

    private static void EmitMethod(SourceWriter writer, IrMethod method, Placement placement)
    {
        var returnType = TypeName(method.ReturnType);
        var methodName = placement.MethodNameOf(method.Signature);
        var receiverType = "global::" + NameConventions.GetCSharpTypeName(method.Receiver);

        var parameters = new List<string> { $"this {receiverType} {ReceiverName}" };
        parameters.AddRange(method.Parameters.Select(p => $"{TypeName(p.Type)} {Escape(p.Name)}"));

        using var methodScope = writer.Block(
            $"public static {returnType} {methodName}({string.Join(", ", parameters)})");

        EmitStatements(
            writer,
            method.Body.Statements,
            new Body(placement, IrMutation.ChangesAMessage(method)) { Taken = NamesDeclaredIn(method) });
    }

    private static string Expression(
        IrExpression expression, Placement placement, string receiverName = ReceiverName) => expression switch
    {
        IrThis => receiverName,
        IrLocalReference local => Escape(local.Local.Name),
        IrParameterReference parameter => Escape(parameter.Parameter.Name),
        IrFieldAccess field => $"{Expression(field.Receiver, placement, receiverName)}.{NameConventions.GetCSharpPropertyName(field.Field)}",
            IrFieldPresence presence => EmitPresence(presence, placement, receiverName),
        IrMethodCall call => EmitCall(call, placement, receiverName),
        IrBinary binary => EmitBinary(binary, placement, receiverName),
        IrIntegerDivision division => EmitIntegerDivision(division, placement, receiverName),
        IrUnary unary => EmitUnary(unary, placement, receiverName),
        IrConversion conversion => EmitConversion(conversion, placement, receiverName),
        IrEnumToNumber number => $"((int){Expression(number.Operand, placement, receiverName)})",
        IrNumberToEnum conversion => EmitNumberToEnum(conversion, placement, receiverName),
        IrEnumMembership membership
            => $"{CSharpRuntime.EnumsTypeName}.IsNamed({Expression(membership.Value, placement, receiverName)})",
        IrEnumValue enumValue => EnumValue(enumValue.Value),
        IrLiteral literal => EmitLiteral(literal),
        IrMessageLiteral literal => MessageLiteral(literal, placement, receiverName),
        IrMapLookup lookup => EmitMapLookup(lookup, placement, receiverName),
        IrMapContains contains
            => $"{Expression(contains.Map, placement, receiverName)}.ContainsKey({Expression(contains.Key, placement, receiverName)})",
        IrMapQuery query => EmitMapQuery(query, placement, receiverName),
        _ => throw new ArgumentOutOfRangeException(nameof(expression), expression, "Unhandled expression."),
    };

    private static string EmitCall(IrMethodCall call, Placement placement, string receiverName)
    {
        var arguments = new List<string> { Expression(call.Receiver, placement, receiverName) };
        arguments.AddRange(call.Arguments.Select(argument => IrMutation.IsPassedAsACopy(call, argument)
            ? StoredValue(argument, placement, receiverName)
            : Expression(argument, placement, receiverName)));

        var methodName = placement.MethodNameOf(call.Target);
        return $"{placement.QualifiedClassOf(call.Target.Receiver)}.{methodName}({string.Join(", ", arguments)})";
    }

    /// <summary>
    /// Emits a presence test (spec 8.4).
    /// </summary>
    /// <remarks>
    /// protoc's C# generator emits <c>HasXxx</c> only for a field carried in a oneof, real or the
    /// synthetic one a proto3 <c>optional</c> creates. A message-typed field has presence without
    /// one, and expresses it by being a nullable reference, so the two cases need different
    /// spellings. Both are what a C# author would write by hand.
    /// </remarks>
    private static string EmitPresence(IrFieldPresence presence, Placement placement, string receiverName)
    {
        var receiver = Expression(presence.Receiver, placement, receiverName);
        var property = NameConventions.GetCSharpPropertyName(presence.Field);

        return presence.Field.FieldType is FieldType.Message or FieldType.Group
            ? $"({receiver}.{property} != null)"
            : $"{receiver}.Has{property}";
    }

}
